#!/bin/sh

. ./common

if [ $# != 1 ]; then
	echo Syntax: $0 test_directory_name ;
	exit 1;
fi

make clean
echo removing test directory $1
rm -r $1

echo removing outputs
rm -f  $OUTPUT_DIR/*

echo removing autogenerated expected outputs
for g in $(ls $EXPECTED_DIR/*.gen)
do
	filename=$(basename $g)
	rm -f $EXPECTED_DIR/${filename%.gen}.out
	rm -f $EXPECTED_DIR/${filename%.gen}.err
done
